In [1]:
import pandas as pd

In [2]:
pip install xlrd

Requirement already satisfied: xlrd in c:\users\neelam sushmitha\anaconda3\lib\site-packages (2.0.1)
Note: you may need to restart the kernel to use updated packages.

In [5]:
df=pd.read_excel(r"C:\Users\NEELAM SUSHMITHA\Downloads\Global Superstore.xls","Orders")
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.570,Critical
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.630,Critical
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.490,Medium
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.160,Medium
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.040,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2014-62366,2014-06-19,2014-06-19,Same Day,KE-16420,Katrina Edelman,Corporate,Kure,Hiroshima,...,OFF-FA-10000746,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.100,5,0.0,4.5000,0.010,Medium
51286,35398,US-2014-102288,2014-06-20,2014-06-24,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,Houston,Texas,...,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,-1.1100,0.010,Medium
51287,40470,US-2013-155768,2013-12-02,2013-12-02,Same Day,LB-16795,Laurel Beltran,Home Office,Oxnard,California,...,OFF-EN-10001219,Office Supplies,Envelopes,"#10- 4 1/8"" x 9 1/2"" Security-Tint Envelopes",22.920,3,0.0,11.2308,0.010,High
51288,9596,MX-2012-140767,2012-02-18,2012-02-22,Standard Class,RB-19795,Ross Baird,Home Office,Valinhos,São Paulo,...,OFF-BI-10000806,Office Supplies,Binders,"Acco Index Tab, Economy",13.440,2,0.0,2.4000,0.003,Medium
51289,6147,MX-2012-134460,2012-05-22,2012-05-26,Second Class,MC-18100,Mick Crebagga,Consumer,Tipitapa,Managua,...,OFF-PA-10004155,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,1.8000,0.002,High

In [36]:
#listing the dataframe top 5 rows
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

In [37]:
#listing the dataframe last 5 rows
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
51285,29002,IN-2014-62366,2014-06-19,2014-06-19,Same Day,KE-16420,Katrina Edelman,Corporate,Kure,Hiroshima,...,OFF-FA-10000746,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.100,5,0.0,4.5000,0.010,Medium
51286,35398,US-2014-102288,2014-06-20,2014-06-24,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,Houston,Texas,...,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,-1.1100,0.010,Medium
51287,40470,US-2013-155768,2013-12-02,2013-12-02,Same Day,LB-16795,Laurel Beltran,Home Office,Oxnard,California,...,OFF-EN-10001219,Office Supplies,Envelopes,"#10- 4 1/8"" x 9 1/2"" Security-Tint Envelopes",22.920,3,0.0,11.2308,0.010,High
51288,9596,MX-2012-140767,2012-02-18,2012-02-22,Standard Class,RB-19795,Ross Baird,Home Office,Valinhos,São Paulo,...,OFF-BI-10000806,Office Supplies,Binders,"Acco Index Tab, Economy",13.440,2,0.0,2.4000,0.003,Medium
51289,6147,MX-2012-134460,2012-05-22,2012-05-26,Second Class,MC-18100,Mick Crebagga,Consumer,Tipitapa,Managua,...,OFF-PA-10004155,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,1.8000,0.002,High

In [9]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'City', 'State', 'Country',
       'Postal Code', 'Market', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping Cost', 'Order Priority'],
      dtype='object')

In [10]:
df.dtypes

Row ID                     int64
Order ID                  object
Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
City                      object
State                     object
Country                   object
Postal Code              float64
Market                    object
Region                    object
Product ID                object
Category                  object
Sub-Category              object
Product Name              object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
Shipping Cost            float64
Order Priority            object
dtype: object

In [12]:
df.shape

(51290, 24)

In [13]:

df["Profit"]

0        762.1845
1       -288.7650
2        919.9710
3        -96.5400
4        311.5200
           ...
51285      4.5000
51286     -1.1100
51287     11.2308
51288      2.4000
51289      1.8000
Name: Profit, Length: 51290, dtype: float64

In [38]:
#getting the mean of one continous variable column
df["Profit"].mean()

28.610982477675964

In [39]:
#getting the median of one continous variable column
df["Profit"].median()

9.24

In [40]:
#getting the mode of one categorical variable column
df["Order Priority"].mode()

0    Medium
Name: Order Priority, dtype: object

In [41]:
#describing the continous variable column
df["Profit"].describe()

count    51290.000000
mean        28.610982
std        174.340972
min      -6599.978000
25%          0.000000
50%          9.240000
75%         36.810000
max       8399.976000
Name: Profit, dtype: float64

In [42]:
#describing all continous variables columns
df.describe()

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit,Shipping Cost
count,51290.00000,51290,51290,9994.000000,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000
mean,25645.50000,2013-05-11 21:26:49.155781120,2013-05-15 20:42:42.745174528,55190.379428,246.490581,3.476545,0.142908,28.610982,26.375818
min,1.00000,2011-01-01 00:00:00,2011-01-03 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000,0.002000
25%,12823.25000,2012-06-19 00:00:00,2012-06-23 00:00:00,23223.000000,30.758625,2.000000,0.000000,0.000000,2.610000
50%,25645.50000,2013-07-08 00:00:00,2013-07-12 00:00:00,56430.500000,85.053000,3.000000,0.000000,9.240000,7.790000
75%,38467.75000,2014-05-22 00:00:00,2014-05-26 00:00:00,90008.000000,251.053200,5.000000,0.200000,36.810000,24.450000
max,51290.00000,2014-12-31 00:00:00,2015-01-07 00:00:00,99301.000000,22638.480000,14.000000,0.850000,8399.976000,933.570000
std,14806.29199,NaN,NaN,32063.693350,487.565361,2.278766,0.212280,174.340972,57.296810

In [43]:
#describing all continous variables columns including categorical variable columns
df.describe(include="all")

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
count,51290.00000,51290,51290,51290,51290,51290,51290,51290,51290,51290,...,51290,51290,51290,51290,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000,51290
unique,NaN,25035,NaN,NaN,4,1590,795,3,3636,1094,...,10292,3,17,3788,NaN,NaN,NaN,NaN,NaN,4
top,NaN,CA-2014-100111,NaN,NaN,Standard Class,PO-18850,Muhammed Yedwab,Consumer,New York City,California,...,OFF-AR-10003651,Office Supplies,Binders,Staples,NaN,NaN,NaN,NaN,NaN,Medium
freq,NaN,14,NaN,NaN,30775,97,108,26518,915,2001,...,35,31273,6152,227,NaN,NaN,NaN,NaN,NaN,29433
mean,25645.50000,NaN,2013-05-11 21:26:49.155781120,2013-05-15 20:42:42.745174528,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,246.490581,3.476545,0.142908,28.610982,26.375818,NaN
min,1.00000,NaN,2011-01-01 00:00:00,2011-01-03 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.444000,1.000000,0.000000,-6599.978000,0.002000,NaN
25%,12823.25000,NaN,2012-06-19 00:00:00,2012-06-23 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,30.758625,2.000000,0.000000,0.000000,2.610000,NaN
50%,25645.50000,NaN,2013-07-08 00:00:00,2013-07-12 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,85.053000,3.000000,0.000000,9.240000,7.790000,NaN
75%,38467.75000,NaN,2014-05-22 00:00:00,2014-05-26 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,251.053200,5.000000,0.200000,36.810000,24.450000,NaN
max,51290.00000,NaN,2014-12-31 00:00:00,2015-01-07 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,22638.480000,14.000000,0.850000,8399.976000,933.570000,NaN
std,14806.29199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,487.565361,2.278766,0.212280,174.340972,57.296810,NaN

In [23]:
df["Order Priority"]

0        Critical
1        Critical
2          Medium
3          Medium
4        Critical
           ...
51285      Medium
51286      Medium
51287        High
51288      Medium
51289        High
Name: Order Priority, Length: 51290, dtype: object

In [44]:
#getting distinct of categorical variable column
df["Order Priority"].unique()
# array(['Critical', 'Medium', 'High', 'Low'], dtype=object)

array(['Critical', 'Medium', 'High', 'Low'], dtype=object)

In [45]:
#getting the number of null values in the dataframe
df.isnull().sum()

Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
City                  0
State                 0
Country               0
Postal Code       41296
Market                0
Region                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Shipping Cost         0
Order Priority        0
dtype: int64

In [26]:
#applying filter on a continous variable column
df[df["Profit"]>1000]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
8,40155,CA-2014-135909,2014-10-14,2014-10-21,Standard Class,JW-15220,Jane Waco,Corporate,Sacramento,California,...,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,5083.96,5,0.2,1906.4850,867.69000,Low
12,45794,SA-2011-1830,2011-12-27,2011-12-29,Second Class,MM-7260,Magdelene Morse,Consumer,Jizan,Jizan,...,TEC-CIS-10001717,Technology,Phones,"Cisco Smart Phone, with Caller ID",2616.96,4,0.0,1151.4000,832.41000,Critical
14,27704,IN-2013-73951,2013-06-06,2013-06-08,Second Class,PF-19120,Peter Fuller,Consumer,Mudanjiang,Heilongjiang,...,OFF-AP-10003500,Office Supplies,Appliances,"KitchenAid Microwave, White",3701.52,12,0.0,1036.0800,804.54000,Critical
17,12069,ES-2014-1651774,2014-09-08,2014-09-14,Standard Class,PJ-18835,Patrick Jones,Corporate,Prato,Tuscany,...,OFF-AP-10004512,Office Supplies,Appliances,"Hoover Stove, Red",7958.58,14,0.0,3979.0800,778.32000,Low
23,13528,ES-2013-2860574,2013-02-27,2013-03-01,Second Class,LB-16795,Laurel Beltran,Home Office,Edinburgh,Scotland,...,OFF-AP-10003590,Office Supplies,Appliances,"KitchenAid Refrigerator, Black",5273.70,10,0.0,1898.4000,730.91000,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13013,23447,IN-2011-77892,2011-04-02,2011-04-08,Standard Class,HL-15040,Hunter Lopez,Consumer,Rajshahi,Rajshahi,...,TEC-PH-10001751,Technology,Phones,"Samsung Smart Phone, Cordless",3195.00,5,0.0,1150.2000,23.95000,Medium
14843,39450,CA-2014-140151,2014-03-24,2014-03-26,First Class,RB-19360,Raymond Buch,Consumer,Seattle,Washington,...,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.96,4,0.0,6719.9808,20.00054,Medium
16062,39785,CA-2013-158841,2013-02-02,2013-02-04,Second Class,SE-20110,Sanjit Engle,Consumer,Arlington,Virginia,...,TEC-MA-10001127,Technology,Machines,HP Designjet T520 Inkjet Large Format Printer ...,8749.95,5,0.0,2799.9840,17.83000,Critical
19307,21850,IN-2011-50060,2011-09-06,2011-09-13,Standard Class,MC-17575,Matt Collins,Consumer,Yancheng,Jiangsu,...,FUR-BO-10000035,Furniture,Bookcases,"Dania Classic Bookcase, Pine",2472.66,6,0.0,1038.4200,13.25000,Medium
39564,12383,ES-2012-5671193,2012-05-29,2012-05-29,Same Day,MG-18145,Mike Gockenbach,Consumer,Luton,England,...,TEC-PH-10004823,Technology,Phones,"Nokia Smart Phone, Full Size",5724.54,9,0.0,2461.3200,2.34000,Medium

In [27]:
df[df["Profit"]>1000]["Profit"]

8        1906.4850
12       1151.4000
14       1036.0800
17       3979.0800
23       1898.4000
           ...
13013    1150.2000
14843    6719.9808
16062    2799.9840
19307    1038.4200
39564    2461.3200
Name: Profit, Length: 147, dtype: float64

In [28]:
#applying multiple filter on a continous variable column
df[(df["Profit"]>1000) & (df["Shipping Cost"]<600)]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
66,16653,IT-2014-4540740,2014-12-07,2014-12-08,First Class,DK-13090,Dave Kipp,Consumer,Seville,Andalusía,...,FUR-BO-10004999,Furniture,Bookcases,"Safco Classic Bookcase, Metal",2188.05,5,0.0,1050.1500,593.91000,High
70,21191,IN-2013-40050,2013-06-07,2013-06-09,First Class,AS-10225,Alan Schoenberger,Corporate,Jinan,Shandong,...,FUR-CH-10003232,Furniture,Chairs,"Harbour Creations Executive Leather Armchair, ...",3298.26,7,0.0,1055.2500,589.36000,High
72,49085,CG-2013-6110,2013-03-29,2013-03-31,Second Class,BW-1065,Barry Weirich,Consumer,Kananga,Kasai-Occidental,...,FUR-HAR-10002873,Furniture,Chairs,"Harbour Creations Executive Leather Armchair, ...",3808.80,8,0.0,1523.5200,588.13000,High
76,31806,CA-2012-145352,2012-03-16,2012-03-22,Standard Class,CM-12385,Christopher Martinez,Consumer,Atlanta,Georgia,...,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,6354.95,5,0.0,3177.4750,581.12000,Medium
78,24443,IN-2011-62506,2011-11-09,2011-11-11,Second Class,SZ-20035,Sam Zeldin,Home Office,Nanchong,Sichuan,...,TEC-CO-10002526,Technology,Copiers,"Sharp Wireless Fax, Digital",3200.04,9,0.0,1183.9500,576.71000,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13013,23447,IN-2011-77892,2011-04-02,2011-04-08,Standard Class,HL-15040,Hunter Lopez,Consumer,Rajshahi,Rajshahi,...,TEC-PH-10001751,Technology,Phones,"Samsung Smart Phone, Cordless",3195.00,5,0.0,1150.2000,23.95000,Medium
14843,39450,CA-2014-140151,2014-03-24,2014-03-26,First Class,RB-19360,Raymond Buch,Consumer,Seattle,Washington,...,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.96,4,0.0,6719.9808,20.00054,Medium
16062,39785,CA-2013-158841,2013-02-02,2013-02-04,Second Class,SE-20110,Sanjit Engle,Consumer,Arlington,Virginia,...,TEC-MA-10001127,Technology,Machines,HP Designjet T520 Inkjet Large Format Printer ...,8749.95,5,0.0,2799.9840,17.83000,Critical
19307,21850,IN-2011-50060,2011-09-06,2011-09-13,Standard Class,MC-17575,Matt Collins,Consumer,Yancheng,Jiangsu,...,FUR-BO-10000035,Furniture,Bookcases,"Dania Classic Bookcase, Pine",2472.66,6,0.0,1038.4200,13.25000,Medium
39564,12383,ES-2012-5671193,2012-05-29,2012-05-29,Same Day,MG-18145,Mike Gockenbach,Consumer,Luton,England,...,TEC-PH-10004823,Technology,Phones,"Nokia Smart Phone, Full Size",5724.54,9,0.0,2461.3200,2.34000,Medium

In [29]:
df[(df["Profit"]>1000) & (df["Shipping Cost"]<600)][["Profit","Shipping Cost"]]

          Profit  Shipping Cost
66     1050.1500      593.91000
70     1055.2500      589.36000
72     1523.5200      588.13000
76     3177.4750      581.12000
78     1183.9500      576.71000
...          ...            ...
13013  1150.2000       23.95000
14843  6719.9808       20.00054
16062  2799.9840       17.83000
19307  1038.4200       13.25000
39564  2461.3200        2.34000

[132 rows x 2 columns]

In [30]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'City', 'State', 'Country',
       'Postal Code', 'Market', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping Cost', 'Order Priority'],
      dtype='object')

In [31]:
df.head()["Segment"]

0       Consumer
1      Corporate
2       Consumer
3    Home Office
4       Consumer
Name: Segment, dtype: object

In [32]:
#applying filter on a categorical variable column
df[df["Segment"]=="Consumer"]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.570,Critical
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.490,Medium
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.040,Critical
6,30570,IN-2011-81826,2011-11-07,2011-11-09,First Class,TS-21340,Toby Swindell,Consumer,Porirua,Wellington,...,FUR-CH-10004050,Furniture,Chairs,"Novimex Executive Leather Armchair, Adjustable",1822.080,4,0.0,564.8400,894.770,Critical
7,31192,IN-2012-86369,2012-04-14,2012-04-18,Standard Class,MB-18085,Mick Brown,Consumer,Hamilton,Waikato,...,FUR-TA-10002958,Furniture,Tables,"Chromcraft Conference Table, Fully Assembled",5244.840,6,0.0,996.4800,878.380,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51277,37361,CA-2012-111780,2012-12-25,2012-12-30,Second Class,RA-19285,Ralph Arnett,Consumer,San Diego,California,...,OFF-PA-10001667,Office Supplies,Paper,Great White Multi-Use Recycled Paper (20Lb. an...,17.940,3,0.0,8.0730,0.020,High
51278,43818,NI-2011-4700,2011-09-08,2011-09-10,Second Class,PO-8865,Patrick O'Donnell,Consumer,Lagos,Lagos,...,OFF-STA-10001791,Office Supplies,Art,"Stanley Highlighters, Water Color",5.364,1,0.7,-6.4560,0.020,High
51281,6039,MX-2014-169530,2014-06-09,2014-06-11,First Class,HG-15025,Hunter Glantz,Consumer,Bragança Paulista,São Paulo,...,OFF-PA-10002418,Office Supplies,Paper,"Green Bar Message Books, Multicolor",84.000,5,0.0,9.2000,0.019,High
51286,35398,US-2014-102288,2014-06-20,2014-06-24,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,Houston,Texas,...,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,-1.1100,0.010,Medium
51289,6147,MX-2012-134460,2012-05-22,2012-05-26,Second Class,MC-18100,Mick Crebagga,Consumer,Tipitapa,Managua,...,OFF-PA-10004155,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,1.8000,0.002,High

In [33]:
 df[df["Segment"]=="Consumer"]["Segment"]

0        Consumer
2        Consumer
4        Consumer
6        Consumer
7        Consumer
           ...
51277    Consumer
51278    Consumer
51281    Consumer
51286    Consumer
51289    Consumer
Name: Segment, Length: 26518, dtype: object

In [34]:
#applying multiple filter on a categorical variable column
df[(df["Segment"]=="Consumer") & (df["State"]=="New York")]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
36,36423,CA-2011-160766,2011-09-14,2011-09-14,Same Day,DM-13015,Darrin Martin,Consumer,New York City,New York,...,TEC-MA-10003979,Technology,Machines,Ativa V4110MDD Micro-Cut Shredder,2799.960,4,0.0,1371.9804,675.15,High
50,40046,US-2012-163825,2012-06-16,2012-06-19,First Class,LC-16885,Lena Creighton,Consumer,New York City,New York,...,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,3050.376,3,0.2,1143.8910,632.05,High
121,37923,CA-2011-145541,2011-12-14,2011-12-21,Standard Class,TB-21400,Tom Boeckenhauer,Consumer,New York City,New York,...,TEC-MA-10001127,Technology,Machines,HP Designjet T520 Inkjet Large Format Printer ...,6999.960,4,0.0,2239.9872,499.55,Medium
147,32998,CA-2012-114069,2012-07-13,2012-07-15,Second Class,ND-18370,Natalie DeCherney,Consumer,New York City,New York,...,FUR-CH-10000595,Furniture,Chairs,Safco Contoured Stacking Chairs,1931.040,9,0.1,321.8400,477.15,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51060,35119,CA-2014-141873,2014-10-10,2014-10-15,Standard Class,HG-14845,Harry Greene,Consumer,New York City,New York,...,OFF-BI-10003655,Office Supplies,Binders,Durable Pressboard Binders,18.240,6,0.2,6.1560,0.13,Medium
51068,39813,CA-2013-132899,2013-04-08,2013-04-12,Standard Class,SF-20200,Sarah Foster,Consumer,New York City,New York,...,OFF-AR-10002833,Office Supplies,Art,Newell 322,3.640,2,0.0,0.9828,0.13,Medium
51110,36503,CA-2012-102015,2012-09-12,2012-09-18,Standard Class,TM-21010,Tamara Manning,Consumer,Auburn,New York,...,OFF-FA-10000490,Office Supplies,Fasteners,"OIC Binder Clips, Mini, 1/4"" Capacity, Black",1.240,1,0.0,0.5828,0.11,Medium
51165,32881,CA-2012-131338,2012-08-09,2012-08-12,First Class,NP-18325,Naresj Patel,Consumer,New York City,New York,...,FUR-FU-10001706,Furniture,Furnishings,Longer-Life Soft White Bulbs,6.160,2,0.0,2.9568,0.09,Medium
51211,38308,US-2011-135881,2011-05-23,2011-05-27,Standard Class,GT-14710,Greg Tran,Consumer,New York City,New York,...,OFF-SU-10003002,Office Supplies,Supplies,Letter Slitter,5.040,2,0.0,0.1512,0.07,Medium

In [35]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'City', 'State', 'Country',
       'Postal Code', 'Market', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping Cost', 'Order Priority'],
      dtype='object')

In [46]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

In [51]:
df["My_column"]=0
df["My_column"]

0        0
1        0
2        0
3        0
4        0
        ..
51285    0
51286    0
51287    0
51288    0
51289    0
Name: My_column, Length: 51290, dtype: int64

In [52]:
#getting a value of particular cell of sheet
df.loc[3,"Sub-Category"]

'Phones'

In [53]:
df.loc[2,"Sub-Category"]

'Phones'

In [54]:
df.loc[0,"Sub-Category"]

'Accessories'

In [55]:
 df.loc[1,"Sub-Category"]

'Chairs'

In [56]:
#modifying the value of a particular cell
df.loc[1,"Sub-Category"]=df.loc[1,"Sub-Category"]+"mychange"
df.loc[1,"Sub-Category"]

'Chairsmychange'

In [57]:
df.loc[0:2,"Sub-Category"]

0       Accessories
1    Chairsmychange
2            Phones
Name: Sub-Category, dtype: object

In [58]:
df.iloc[1,16]

'Chairsmychange'

In [59]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'City', 'State', 'Country',
       'Postal Code', 'Market', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping Cost', 'Order Priority', 'My_column'],
      dtype='object')

In [60]:
df.head()["My_column"]

0    0
1    0
2    0
3    0
4    0
Name: My_column, dtype: int64

In [62]:
#modifying the value of particular cells
for i in range(df.shape[0]):
    if i%2 == 1:
        df.loc[i,"My_column"]=-1

In [63]:
df.head()["My_column"]

0    0
1   -1
2    0
3   -1
4    0
Name: My_column, dtype: int64

In [64]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,My_column
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical,0
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,Furniture,Chairsmychange,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical,-1
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium,0
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium,-1
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical,0